# Generated by Django 5.2.17 on 2026-09-16 14:05

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('league', '0005_ruletemplate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DraftActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('status', models.CharField(choices=[('setup', '准备'), ('active', '进行中'), ('complete', '已完成')], default='setup', max_length=12)),
                ('revision', models.PositiveIntegerField(default=1)),
                ('document', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='draft_activities', to='league.event')),
            ],
        ),
        migrations.CreateModel(
            name='DraftAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('action', models.CharField(max_length=40)),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='team_draft.draftactivity')),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='draftactivity',
            constraint=models.UniqueConstraint(condition=models.Q(('event__isnull', False), ('status__in', ['setup', 'active'])), fields=('event',), name='draft_one_open_activity_per_event'),
        ),
        migrations.AddConstraint(
            model_name='draftaudit',
            constraint=models.UniqueConstraint(fields=('activity', 'revision'), name='draft_activity_revision_unique'),
        ),
    ]
