// v3: roster entry points, lineups and statistics. Uses only this page's demo state.
tournaments.forEach(x=>{x.players.forEach((p,i)=>p.number??='P'+String(i+1).padStart(3,'0'));x.teams.forEach((team,i)=>{team.color??=['#155e49','#b54b40','#5c7292','#796087'][i%4]})});
let boardFocus=null;
const teamName=(x,id)=>x.teams.find(v=>v.id===id)?.name||'待分配';
const playerLabel=p=>p.name+' · '+(p.number||p.id);
const pct=x=>x===null?'—':(x*100).toFixed(1)+'%';
const decimal=x=>x===null?'—':x.toFixed(2);
function managementSteps(){return `<div class="workflow"><span>① 创建赛事</span><span>② 建队伍（团体赛）</span><span>③ 添加选手 / 分配队伍</span><span>④ 选择四人阵容</span><span>⑤ 录入战果</span></div>`}
function renderRoster(editId){const x=t(),edit=x.players.find(p=>p.id===editId);
 $('content').innerHTML=header('选手录入与赛事报名',esc(x.name)+' · 此处录入的选手只报名当前赛事。')+managementSteps()+`<div class="roster-layout"><form id="player-form" class="card"><div class="card-head"><h2>${edit?'编辑参赛选手':'添加参赛选手'}</h2><span class="pill">${x.type==='team'?'团体赛':'个人赛'}</span></div><div class="form-stack"><label>选手姓名 / 昵称<input id="p-name" value="${esc(edit?.name||'')}" required maxlength="40" placeholder="输入公开展示名称"></label><label>赛事报名编号<input id="p-number" value="${esc(edit?.number||'')}" required maxlength="20" placeholder="如 HQL-001（本赛事唯一）"></label>${x.type==='team'?`<label>所属队伍<select id="p-team">${options([{id:'',name:'待分配（暂不能出场）'},...x.teams.map(team=>({id:team.id,name:team.name+(team.active===false?' · 已停用':'')}))],edit?.teamId||'')}</select></label><p class="subtle">先在“队伍管理”创建队伍。修改归属只影响之后选择的阵容，已录对局保留当场队伍。</p>`:''}<label>报名状态<select id="p-active"><option value="yes" ${edit?.active!==false?'selected':''}>可参赛</option><option value="no" ${edit?.active===false?'selected':''}>停用（保留历史）</option></select></label></div><div class="actions">${edit?'<button type="button" class="button secondary" id="cancel-player">取消编辑</button>':''}<button class="button" type="submit">${edit?'保存选手修改':'添加选手并报名'}</button></div></form><div class="card"><div class="card-head"><h2>已报名选手 · ${x.players.length}</h2><span class="pill green">可出场 ${HQL.eligiblePlayers(x).length}</span></div><div class="member-search"><label>搜索名单<input id="roster-search" placeholder="姓名、编号、队伍"></label></div><div class="scroll-table"><table><thead><tr><th>选手</th><th>队伍 / 状态</th><th>操作</th></tr></thead><tbody id="roster-rows"></tbody></table></div><p class="helper" style="margin-top:16px">可允许同名选手，以报名编号区分。停用不删除既有赛果。</p></div></div>`;
 const draw=()=>{const query=$('roster-search').value.trim();const rows=x.players.filter(p=>(p.name+' '+p.number+' '+teamName(x,p.teamId)).includes(query));$('roster-rows').innerHTML=rows.map(p=>`<tr><td><strong>${esc(p.name)}</strong><small class="subtle">${esc(p.number||p.id)}</small></td><td>${esc(x.type==='team'?teamName(x,p.teamId):'个人参赛')}<small class="subtle">${p.active===false?'已停用':HQL.eligiblePlayers(x).some(v=>v.id===p.id)?'可出场':'待分配有效队伍'}</small></td><td><button class="button secondary" data-edit-player="${p.id}">编辑</button></td></tr>`).join('')||'<tr><td colspan="3" class="empty">暂无匹配选手，请添加或调整搜索。</td></tr>';document.querySelectorAll('[data-edit-player]').forEach(b=>b.onclick=()=>renderRoster(b.dataset.editPlayer))};draw();$('roster-search').oninput=draw;
 $('player-form').onsubmit=e=>{e.preventDefault();safe(()=>{HQL.savePlayer(x,{name:$('p-name').value,number:$('p-number').value,teamId:$('p-team')?.value,active:$('p-active').value==='yes'},editId);renderRoster();toast('参赛选手已保存到当前赛事的演示名单')})};if(edit)$('cancel-player').onclick=()=>renderRoster();
}
function renderTeamAdmin(editId){const x=t();if(x.type!=='team'){$('content').innerHTML=header('队伍管理','此赛事为个人赛。')+empty('无需创建队伍，直接进入“选手管理”添加参赛选手。');return}const edit=x.teams.find(team=>team.id===editId);
 $('content').innerHTML=header('队伍与成员管理',esc(x.name)+' · 队伍独立属于本赛事。')+managementSteps()+`<div class="roster-layout"><form id="team-form" class="card"><div class="card-head"><h2>${edit?'编辑队伍':'创建参赛队伍'}</h2></div><div class="form-stack"><label>队伍名称<input id="team-name" value="${esc(edit?.name||'')}" maxlength="60" required placeholder="例如：青岚队"></label><label>队伍简称<input id="team-short" value="${esc(edit?.short||'')}" maxlength="12" placeholder="用于紧凑榜单"></label><label>代表色<input id="team-color" type="color" value="${esc(edit?.color||'#155e49')}"></label><label>队伍状态<select id="team-active"><option value="yes" ${edit?.active!==false?'selected':''}>参赛中</option><option value="no" ${edit?.active===false?'selected':''}>停用（保留历史）</option></select></label></div><div class="actions">${edit?'<button class="button secondary" id="cancel-team" type="button">取消编辑</button>':''}<button class="button">${edit?'保存队伍修改':'创建队伍'}</button></div></form><div class="team-management-grid">${x.teams.map(team=>`<article class="card team-profile" style="--team:${esc(team.color||'#155e49')}"><div class="team-profile-head"><span class="team-emblem">${esc((team.short||team.name).slice(0,2))}</span><div><h2>${esc(team.name)}</h2><p>${team.active===false?'已停用':'参赛中'} · ${x.players.filter(p=>p.teamId===team.id).length} 名成员</p></div></div><div class="member-chips">${x.players.filter(p=>p.teamId===team.id).map(p=>`<span>${esc(playerLabel(p))}${p.active===false?'（停用）':''}</span>`).join('')||'<p class="subtle">尚无成员；去选手管理添加并分配。</p>'}</div><div class="actions"><button class="button secondary" data-edit-team="${team.id}">编辑队伍</button><button class="button" data-add-members="${team.id}">管理成员</button></div></article>`).join('')||empty('还没有队伍，请先创建队伍。')}</div></div>`;
 $('team-form').onsubmit=e=>{e.preventDefault();safe(()=>{HQL.saveTeam(x,{name:$('team-name').value,short:$('team-short').value,color:$('team-color').value,active:$('team-active').value==='yes'},editId);renderTeamAdmin();toast('队伍已保存，可在选手管理中分配成员')})};if(edit)$('cancel-team').onclick=()=>renderTeamAdmin();document.querySelectorAll('[data-edit-team]').forEach(b=>b.onclick=()=>renderTeamAdmin(b.dataset.editTeam));document.querySelectorAll('[data-add-members]').forEach(b=>b.onclick=()=>{page='roster';render();$('p-team').value=b.dataset.addMembers});
}
const renderEntryV2=renderEntry;
renderEntry=function(){renderEntryV2();const x=t(),m=activeMatch();if(!m)return;const locked=m.status==='published'||x.stages.find(s=>s.id===m.stageId).locked;
 if(!locked){const eligible=HQL.eligiblePlayers(x);const panel=document.createElement('form');panel.id='lineup-form';panel.className='lineup-panel';panel.innerHTML=`<h3>本场四名出场选手</h3><p class="subtle">从已报名名单中选择；加入新选手时会重置本场点数为起始点，避免把前一人的战果记到另一人名下。</p><div class="lineup-grid">${m.seats.map((s,i)=>`<label>${['东','南','西','北'][i]}家选手<select id="lineup-${i}">${options(eligible.map(p=>({id:p.id,name:playerLabel(p)+(x.type==='team'?' / '+teamName(x,p.teamId):'')})),s.playerId)}</select></label>`).join('')}</div><button class="button secondary" type="submit">应用本场出场阵容</button>`;document.querySelector('.player-cards').before(panel);panel.onsubmit=e=>{e.preventDefault();safe(()=>{const result=HQL.setLineup(x,m,[0,1,2,3].map(i=>$('lineup-'+i).value));renderEntry();toast(result.resetScores?'阵容已更新，点数已重置，请重新录入':'座次已更新，选手点数随本人保留')})};
  const seated=m.seats.map(s=>x.players.find(p=>p.id===s.playerId)).map(p=>({id:p.id,name:playerLabel(p)}));['penalty-player','yakuman-player'].forEach(id=>{if($(id))$(id).innerHTML=options(seated)});
 }
 m.seats.forEach((s,i)=>$('score-'+i).setAttribute('aria-label',playerLabel(x.players.find(p=>p.id===s.playerId))+'最终点数'));
};
const renderEventsV2=renderEvents;
renderEvents=function(){renderEventsV2();$('content').querySelector('.topline').insertAdjacentHTML('afterend',managementSteps());document.querySelectorAll('[data-enter]').forEach(b=>b.onclick=()=>{current=b.dataset.enter;page='roster';entryId=null;render()})};
function spark(values){if(!values.length)return '<span class="subtle">暂无对局</span>';let total=0;const pts=[0,...values.map(v=>total+=v)],min=Math.min(...pts),max=Math.max(...pts),range=max-min||1;return `<svg viewBox="0 0 130 36" class="spark" role="img" aria-label="按时间顺序的原始累计积分走势"><line x1="0" x2="130" y1="${32-(0-min)/range*28}" y2="${32-(0-min)/range*28}" stroke="#dce4d4"/><polyline fill="none" stroke="currentColor" stroke-width="2" points="${pts.map((p,i)=>(i/(pts.length-1)*130)+','+(32-(p-min)/range*28)).join(' ')}"/></svg>`}
function valueFor(r,key){return key==='total'?r.total:key==='avgPoints'?r.avgPoints:r[key]}
function renderBoard(){const x=t(),kind=page==='teams'?'team':'player';if(kind==='team'&&x.type==='individual'){$('content').innerHTML=header('队伍榜','当前为个人赛。')+empty('个人赛没有队伍榜，请查看个人榜。');return}
 const stage=filters.stage||'all',metric=filters.metric||'raw',sort=filters.sort||'total',min=filters.min===undefined?(kind==='player'?1:0):Number(filters.min),all=HQL.statistics(x,stage,kind,metric);
 const eligible=all.filter(r=>r.games>=min);
 eligible.sort((a,b)=>{const av=valueFor(a,sort),bv=valueFor(b,sort);if(av===null&&bv!==null)return 1;if(bv===null&&av!==null)return -1;return (sort==='avgRank'?1:-1)*((av??0)-(bv??0))||a.name.localeCompare(b.name)});
 eligible.forEach((r,i)=>{r.displayRank=i&&valueFor(r,sort)===valueFor(eligible[i-1],sort)?eligible[i-1].displayRank:i+1;r.previousGap=i?eligible[i-1].total-r.total:0});
 const rows=eligible.filter(r=>(!filters.keyword||r.name.includes(filters.keyword))&&(!filters.team||x.players.find(p=>p.id===r.id)?.teamId===filters.team));
 const invalid=stage==='all'&&metric==='competitive';
 $('content').innerHTML=header(kind==='team'?'队伍积分榜':'个人表现榜',esc(x.name)+' · 参考 M.LEAGUE 的分差、场数与选手统计展示。')+`<div class="stage-tabs">${[{id:'all',name:'全赛事'},...x.stages].map(s=>`<button class="${stage===s.id?'active':''}" data-board-stage="${s.id}">${esc(s.name)}</button>`).join('')}</div>`+filterBar(true)+`<div class="board-extra"><label>排名指标<select id="board-sort">${options([{id:'total',name:'总积分'},...(kind==='player'?[{id:'best',name:'最高终局点数'},{id:'avgRank',name:'平均顺位（越低越好）'},{id:'topRate',name:'头名率'},{id:'topTwo',name:'连对率'},{id:'avoidLast',name:'避四率'},{id:'avgPoints',name:'场均积分'}]:[])],sort)}</select></label><label>最少场数<input id="board-min" type="number" min="0" step="1" value="${min}"></label>${kind==='player'&&x.type==='team'?`<label>当前所属队伍<select id="board-team">${options([{id:'',name:'全部队伍'},...x.teams],filters.team||'')}</select></label>`:''}<button class="button secondary" id="apply-board-extra">更新统计</button></div>`;
 if(invalid){$('content').insertAdjacentHTML('beforeend','<div class="notice error">请选定一个阶段查看竞技分；全赛事展示原始累计。</div>')}else if(!rows.length){$('content').insertAdjacentHTML('beforeend',empty('暂无符合资格或筛选条件的数据；新报名选手尚未出场时，可将最少场数设为 0 查看。'))}else if(kind==='team'){
  $('content').insertAdjacentHTML('beforeend',`<div class="leader-spotlight"><div><div class="eyebrow">TEAM RANKING</div><h2>${esc(eligible[0].name)}</h2><p>当前 ${metric==='competitive'?'阶段竞技':'原始累计'}积分领先</p></div><strong>${fmt(eligible[0].total)}<small>pt</small></strong></div><div class="card scroll-table"><table class="ml-table"><thead><tr><th>排名 / 队伍</th><th>积分</th><th>距前一名</th><th>距榜首</th><th>已赛 / 已排</th><th>最近一场</th><th>原始累计走势</th><th>成员数据</th></tr></thead><tbody>${rows.map(r=>{const team=x.teams.find(v=>v.id===r.id),planned=x.matches.filter(m=>(stage==='all'||m.stageId===stage)&&m.status!=='cancelled'&&m.seats.some(s=>s.teamId===r.id)).length;return `<tr><td><div class="identity"><span class="rank">${r.displayRank}</span><span class="team-emblem small" style="--team:${esc(team.color||'#155e49')}">${esc((team.short||r.name).slice(0,2))}</span><strong>${esc(r.name)}</strong></div></td><td class="big-score ${cls(r.total)}">${fmt(r.total)}</td><td>${r.displayRank===1?'—':(r.previousGap/10).toFixed(1)}</td><td>${((eligible[0].total-r.total)/10).toFixed(1)}</td><td>${r.games} / ${planned}</td><td class="${cls(r.last)}">${r.games?fmt(r.last):'—'}</td><td class="${cls(r.raw)}">${spark(r.scoreHistory)}</td><td><button class="button secondary" data-detail-team="${r.id}">展开成员</button></td></tr>`}).join('')}</tbody></table></div>`)
 }else{
  const keyLabel={total:'积分',best:'最高终局点数',avgRank:'平均顺位',topRate:'头名率',topTwo:'连对率',avoidLast:'避四率',avgPoints:'场均积分'}[sort];
  const scoreDisplay=r=>sort==='total'?fmt(r.total):sort==='best'?(r.best===null?'—':r.best.toLocaleString()+' 点'):sort==='avgRank'?decimal(r.avgRank):sort==='avgPoints'?(r.avgPoints===null?'—':(r.avgPoints/10).toFixed(2)):pct(r[sort]);
  $('content').insertAdjacentHTML('beforeend',`<div class="player-podium">${rows.slice(0,3).map(r=>`<article class="card podium-card"><div class="eyebrow">${r.displayRank} / ${keyLabel}</div><div class="identity"><span class="player-avatar">${esc(r.name.slice(0,1))}</span><h2>${esc(r.name)}</h2></div><p>${x.type==='team'?esc(teamName(x,x.players.find(p=>p.id===r.id).teamId)):'个人参赛'} · ${r.games} 场</p><strong>${scoreDisplay(r)}</strong></article>`).join('')}</div><div class="card scroll-table"><table class="ml-table"><thead><tr><th>排名 / 选手</th><th>积分</th><th>场数</th><th>平均顺位</th><th>1 / 2 / 3 / 4 位</th><th>头名率</th><th>连对率</th><th>避四率</th><th>最高点数</th><th>罚分</th><th>役满</th><th>详情</th></tr></thead><tbody>${rows.map(r=>`<tr><td><div class="identity"><span class="rank">${r.displayRank}</span><div><strong>${esc(r.name)}</strong><small class="subtle">${esc(x.players.find(p=>p.id===r.id).number||r.id)}</small></div></div></td><td class="num ${cls(r.total)}">${fmt(r.total)}</td><td>${r.games}</td><td>${decimal(r.avgRank)}</td><td>${r.places.map(v=>Number.isInteger(v)?v:v.toFixed(2)).join(' / ')}</td><td>${pct(r.topRate)}</td><td>${pct(r.topTwo)}</td><td>${pct(r.avoidLast)}</td><td>${r.best===null?'—':r.best.toLocaleString()}</td><td class="negative">${fmt(r.penalty)}</td><td>${r.yakuman}</td><td><button class="button secondary" data-detail-player="${r.id}">查看</button></td></tr>`).join('')}</tbody></table></div>`)
 }
 $('content').insertAdjacentHTML('beforeend',`<div id="board-details"></div><p class="note">口径：${metric==='competitive'?'含本阶段带入的竞技分':'未压缩的原始累计'}。关键词和队伍筛选保留排名；最少场数决定本统计榜资格。同点的顺位次数按所占名次均分，平均顺位按并列名次中点计算（本程序口径）。</p><div class="notice">和牌率、放铳率、立直率、副露率、平均和牌点数、总局数：未采集逐局记录，当前不展示推算值。</div>`);
 bindFilters(true);const normalFilter=$('apply-filter').onclick;$('apply-filter').onclick=()=>{const extra={sort:$('board-sort').value,min:$('board-min').value,team:$('board-team')?.value||''};filters={...filters,...extra};const staged={stage:$('f-stage').value,metric:$('f-metric').value,keyword:$('f-keyword').value.trim()};filters={...filters,...staged};if(!Number.isInteger(Number(filters.min))||Number(filters.min)<0){toast('最少场数须为非负整数');return}renderBoard()};
 $('apply-board-extra').onclick=$('apply-filter').onclick;document.querySelectorAll('[data-board-stage]').forEach(b=>b.onclick=()=>{filters.stage=b.dataset.boardStage;renderBoard()});document.querySelectorAll('[data-detail-team]').forEach(b=>b.onclick=()=>renderTeamDetail(b.dataset.detailTeam,stage));document.querySelectorAll('[data-detail-player]').forEach(b=>b.onclick=()=>renderPlayerDetail(b.dataset.detailPlayer,stage,metric));
}
function renderTeamDetail(id,stage){const x=t(),team=x.teams.find(v=>v.id===id),rows=HQL.teamContributions(x,id,stage);$('board-details').innerHTML=`<div class="card detail-panel"><div class="card-head"><h2>${esc(team.name)} · 成员贡献</h2><span class="pill">按对局时队伍统计</span></div><div class="scroll-table"><table><thead><tr><th>选手</th><th>场数</th><th>基础贡献</th><th>队伍侧罚分</th><th>净贡献</th><th>成员状态</th></tr></thead><tbody>${rows.map(r=>`<tr><td>${esc(r.name)}</td><td>${r.games}</td><td>${fmt(r.base)}</td><td class="negative">${fmt(r.penalty)}</td><td class="num ${cls(r.total)}">${fmt(r.total)}</td><td>${r.current?'当前成员':'历史成员'}</td></tr>`).join('')}</tbody></table></div><p class="helper" style="margin-top:15px">此处展示实际对局贡献，不平摊队伍阶段带入分。完整选手表现可切换个人榜。</p></div>`;$('board-details').scrollIntoView({behavior:'smooth',block:'start'})}
function renderPlayerDetail(id,stage,metric){const x=t(),r=HQL.statistics(x,stage,'player',metric).find(r=>r.id===id);$('board-details').innerHTML=`<div class="card detail-panel"><div class="card-head"><h2>${esc(r.name)} · 表现详情</h2><span class="pill">${r.games} 场</span></div><div class="metric-grid">${[['总积分',fmt(r.total)],['场均原始积分',r.avgPoints===null?'—':(r.avgPoints/10).toFixed(2)],['平均顺位',decimal(r.avgRank)],['头名率',pct(r.topRate)],['连对率',pct(r.topTwo)],['避四率',pct(r.avoidLast)],['最高终局点数',r.best===null?'—':r.best.toLocaleString()],['罚分',fmt(r.penalty)],['役满次数',r.yakuman]].map(([label,value])=>`<div><span>${label}</span><strong>${value}</strong></div>`).join('')}</div><div class="trend-panel"><span>原始累计走势</span>${spark(r.scoreHistory)}</div></div>`;$('board-details').scrollIntoView({behavior:'smooth',block:'start'})}
const rosterRequestedPage=new URLSearchParams(location.search).get('page');if(Object.hasOwn(pages,rosterRequestedPage))page=rosterRequestedPage;
render();
