# Generated by Django 5.2.17 on 2026-09-06 13:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('revision', models.PositiveIntegerField(default=0)),
                ('decisions', models.JSONField(default=dict)),
                ('archive', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='league.historicalarchive')),
            ],
        ),
        migrations.CreateModel(
            name='HistoryReviewAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revision', models.PositiveIntegerField()),
                ('before', models.JSONField()),
                ('after', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='league.historyreview')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('review', 'revision'), name='history_review_revision_unique')],
            },
        ),
    ]
