# Generated by Django 5.2.17 on 2026-09-07 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0002_historyreview_historyreviewaudit'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryImport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fingerprint', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('archive', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='league.historicalarchive')),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='league.event')),
            ],
        ),
    ]
